name = "restless-sun-f9c3"
main = "worker.js"
compatibility_date = "2024-09-23"

[assets]
directory = "."
exclude = ["node_modules/**", "worker.js", "wrangler.toml", ".git/**", "package*.json", "bun.lockb"]
binding = "ASSETS"

[[kv_namespaces]]
binding = "DOWNLOAD_LOGS"
id = "25247767a45041daa05e8258357ce388"

[[d1_databases]]
binding = "DB"
database_name = "fikat-db"
database_id = "31e8d3cd-6383-40f7-b140-5b5e74615be8"

[triggers]
crons = ["0 * * * *"] # Chạy tự động mỗi 1 tiếng một lần (phút 00 của mỗi giờ) 24/7
